version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
  with-firefox:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
  with-edge:
    docker:
      - image: 'cypress/browsers:node14.10.1-edge88'
workflows:
  build:
      jobs:
        - cypress/install
        - cypress/run:
            name: Chrome
            requires:
              - cypress/install
            executor: with-chrome
            browser: chrome
            record: true
        - cypress/run:
            name: Firefox
            requires:
              - cypress/install
            executor: with-firefox
            browser: firefox
            record: true
        - cypress/run:
            name: Edge
            requires:
              - cypress/install
            executor: with-edge
            browser: edge
            record: true
