version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
      jobs:
        - cypress/install
        - cypress/run:
            name: Chrome
            requires:
              - cypress/install
            executor: cypress/browsers:node14.17.0-chrome91-ff89
            browser: chrome
            record: true
        - cypress/run:
            name: Firefox
            requires:
              - cypress/install
            executor: cypress/browsers:node14.17.0-chrome91-ff89
            browser: firefox
            record: true
        - cypress/run:
            name: Edge
            requires:
              - cypress/install
            executor: cypress/browsers:node14.10.1-edge88
            browser: edge
            record: true
